name = "globe"
version = "0.1.0"
description = "Gleam Compiler Backend"

licences = ["MIT"]
repository = { type = "github", user = "Willyboar", repo = "globe" }

[dependencies]
gleam_stdlib = "~> 0.29"

[dev-dependencies]
gleeunit = "~> 0.10"
